"""
Week 3: Physics-Constrained Conformal Projection (Molecular)
=============================================================
Vijay - Team PVAV

Tasks:
    1. Implement projection onto the energy-conservation constraint manifold
       for molecular dynamics (quadratic constraint -> closed-form projection).
       -> src/physics_projection.py: project_forces_energy_constraint()

    2. Apply projection to MD conformal sets. Measure empirical coverage
       before and after projection. Record coverage loss.
       -> run_conformal_with_projection() below

    3. Compute the epsilon relaxation bound: given calibration set's energy
       violation distribution, compute predicted coverage loss. Compare
       predicted vs. empirical coverage loss.
       -> src/physics_projection.py: compute_epsilon_relaxation_bound()

    4. Write formal proof for quadratic constraint case (energy conservation).
       -> docs/week3_proof_quadratic.md (generated by write_proof_document())

REVISION (post-Kiran feedback):
    E_target is now computed from TRUE calibration forces (cal_F), not the
    surrogate's own predictions (cal_pred).

REVISION 2 (post-Kiran feedback, round 2):
    compute_epsilon_relaxation_bound() now also takes test_F, so the
    epsilon-relaxed bound is validated against held-out test violations
    instead of the same calibration data it was derived from.

REVISION 3 (post-Kiran feedback, round 3 -- uracil / DFT energy):
    E_target is now derived from TRUE DFT energies (cal_E), not purely
    from the force-space statistic ||F||^2. Previously cal_E was loaded
    and used only for the R^2 diagnostic in fit_energy_force_relationship,
    never for the actual projection target. Now the fitted linear
    relationship between ||F||^2 and true energy is inverted to find the
    ||F||^2 value corresponding to the mean TRUE DFT energy, and that is
    used as E_target. This changes E_target (and therefore
    coverage-after-projection) for ALL FOUR molecules, not just uracil --
    rerun --all and re-check every row of Table 1, not just uracil's.

Usage:
    python molecular_week3.py                  # aspirin, alpha=0.10 and 0.05
    python molecular_week3.py --molecule ethanol
    python molecular_week3.py --all
    python molecular_week3.py --alpha 0.10

Output:
    results/molecular/<molecule>_conformal_projected_indist.pt
    results/molecular/<molecule>_conformal_projected_indist_alpha010.pt
    results/molecular/<molecule>_conformal_projected_indist_alpha005.pt
    results/molecular/week3_projection_results.pt
    docs/week3_proof_quadratic.md
"""

import argparse
import os
import sys
import time

import numpy as np
import torch
import torch.nn as nn

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
from conformal import SplitConformal, TrajectoryNormScore
from physics_projection import (
    compute_energy_from_forces,
    fit_energy_force_relationship,
    project_forces_energy_constraint_batched,
    compute_epsilon_relaxation_bound,
)


MOLECULE_FILES = {
    "aspirin":       "data/md17/md17_aspirin.npz",
    "ethanol":       "data/md17/md17_ethanol.npz",
    "uracil":        "data/md17/md17_uracil.npz",
    "malonaldehyde": "data/md17/md17_malonaldehyde.npz",
}


def load_md17(molecule: str, seed: int = 42):
    path = MOLECULE_FILES[molecule]
    if not os.path.exists(path):
        raise FileNotFoundError(f"MD17 file not found: {path}")

    data = np.load(path)
    R = torch.tensor(data["R"], dtype=torch.float32)
    F = torch.tensor(data["F"], dtype=torch.float32)
    E_raw = data["E"]
    if E_raw.ndim > 1:
        print(f"  NOTE: raw E shape is {E_raw.shape}, flattening to 1D")
    E = torch.tensor(E_raw, dtype=torch.float32).reshape(-1)

    N = len(R)
    rng = np.random.RandomState(seed)
    idx = rng.permutation(N)
    n_train = int(0.70 * N)
    n_cal   = int(0.15 * N)
    train_idx = idx[:n_train]
    cal_idx   = idx[n_train : n_train + n_cal]
    test_idx  = idx[n_train + n_cal :]

    print(f"Molecule: {molecule}")
    print(f"  Total snapshots    : {N}")
    print(f"  Train / Cal / Test : {len(train_idx)} / {len(cal_idx)} / {len(test_idx)}")

    return (
        R[train_idx], R[cal_idx], R[test_idx],
        F[train_idx], F[cal_idx], F[test_idx],
        E[train_idx], E[cal_idx], E[test_idx],
    )


class MolecularSurrogate(nn.Module):
    def __init__(self, n_atoms: int, hidden: int = 256, dropout_p: float = 0.1):
        super().__init__()
        self.n_atoms = n_atoms
        in_dim = n_atoms * 3
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden), nn.SiLU(), nn.Dropout(p=dropout_p),
            nn.Linear(hidden, hidden), nn.SiLU(), nn.Dropout(p=dropout_p),
            nn.Linear(hidden, hidden), nn.SiLU(), nn.Dropout(p=dropout_p),
            nn.Linear(hidden, in_dim),
        )

    def forward(self, R: torch.Tensor) -> torch.Tensor:
        batch = R.shape[0]
        return self.net(R.reshape(batch, -1)).reshape(batch, self.n_atoms, 3)


def train_surrogate(model, train_R, train_F, epochs=30, lr=1e-3, batch_size=64):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()
    N = len(train_R)
    model.train()
    for epoch in range(epochs):
        perm = torch.randperm(N)
        epoch_loss = 0.0
        for start in range(0, N, batch_size):
            idx = perm[start : start + batch_size]
            optimizer.zero_grad()
            loss = loss_fn(model(train_R[idx]), train_F[idx])
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * len(idx)
        if (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1:3d}/{epochs}  loss={epoch_loss/N:.6f}")
    model.eval()
    return model


def get_predictions(model, R, batch_size=256):
    model.eval()
    preds = []
    with torch.no_grad():
        for start in range(0, len(R), batch_size):
            preds.append(model(R[start : start + batch_size]))
    return torch.cat(preds, dim=0)


def run_conformal_with_projection(
    model, cal_R, cal_F, cal_E, test_R, test_F, test_E, alpha, molecule
) -> dict:
    """
    Calibrate conformal predictor, then measure coverage before and after
    projecting test predictions onto the energy conservation manifold.

    CHANGED (round 3): E_target is now derived from TRUE DFT energies
    (cal_E), not purely from the ||F||^2 force statistic. We fit
    E_centered = slope * ||F||^2 + intercept on true calibration data
    (fit_energy_force_relationship), then invert it at E_centered = 0
    (i.e. the mean true DFT energy) to get the ||F||^2 value that
    corresponds to that energy:

        E_target = -intercept / slope

    This ties the projection manifold to the molecule's actual energy
    scale instead of an internally-consistent-but-physically-arbitrary
    average of ||F||^2. The old force-only target and the even older
    self-referential (prediction-based) target are both still printed
    for comparison, but only the new DFT-derived target is used for
    the actual projection.
    """
    print(f"\n--- Conformal + Energy Projection (alpha={alpha}, target={1-alpha:.0%}) ---")

    cal_pred  = get_predictions(model, cal_R)
    test_pred = get_predictions(model, test_R)

    # NEW: derive E_target from true DFT energies via the fitted
    # linear relationship between ||F||^2 and true energy.
    fit = fit_energy_force_relationship(cal_F, cal_E)
    if abs(fit["slope"]) < 1e-8:
        raise ValueError(
            f"Degenerate energy-force fit for {molecule}: slope near zero "
            f"({fit['slope']:.2e}). Cannot invert to find a DFT-energy-derived "
            f"target. Falling back to the force-only target would silently "
            f"reintroduce the issue this fix addresses -- investigate the fit "
            f"for this molecule instead of catching this error."
        )
    E_target_scalar = -fit["intercept"] / fit["slope"]

    # Old targets, kept only for comparison in the printout.
    E_target_force_proxy_only = compute_energy_from_forces(cal_F).mean().item()
    E_target_self_referential = compute_energy_from_forces(cal_pred).mean().item()

    print(f"  Energy target (from TRUE DFT energies via fit) : {E_target_scalar:.4f}")
    print(f"  (prior force-proxy-only target was)             : {E_target_force_proxy_only:.4f}")
    print(f"  (original self-referential pred-based target)   : {E_target_self_referential:.4f}")
    print(f"  Fit quality (R^2) backing this target            : {fit['r_squared']:.4f}")

    score_fn = TrajectoryNormScore(normalize_by_length=True)
    cp = SplitConformal(score_fn, alpha=alpha)
    cp.calibrate(cal_pred, cal_F)

    eval_before     = cp.evaluate(test_pred, test_F)
    coverage_before = eval_before["coverage"]
    print(f"\n  Coverage BEFORE projection: {coverage_before:.1%}")

    print(f"  Projecting {len(test_pred)} test predictions onto energy manifold...")
    t0 = time.time()
    test_pred_projected = project_forces_energy_constraint_batched(
        test_pred, E_target_scalar
    )
    print(f"  Projection complete in {time.time() - t0:.1f}s")

    eval_after     = cp.evaluate(test_pred_projected, test_F)
    coverage_after = eval_after["coverage"]
    coverage_loss  = coverage_before - coverage_after
    print(f"  Coverage AFTER projection : {coverage_after:.1%}")
    print(f"  Empirical coverage loss   : {coverage_loss:+.1%}")

    return {
        "surrogate":               "molecular",
        "method":                  "conformal_projected",
        "split":                   "indist",
        "molecule":                molecule,
        "alpha":                   alpha,
        "coverage_before":         coverage_before,
        "coverage_after":          coverage_after,
        "coverage_loss_empirical": coverage_loss,
        "target_coverage":         1 - alpha,
        "mean_width_before":       eval_before["mean_width"],
        "mean_width_after":        eval_after["mean_width"],
        "threshold":               cp.threshold,
        "cal_scores":              cp.cal_scores,
        "n_cal":                   len(cal_R),
        "n_test":                  len(test_R),
        "test_pred_raw":           test_pred,
        "test_pred_projected":     test_pred_projected,
        "ground_truth":            test_F,
        "scores_before":           eval_before["test_scores"],
        "scores_after":            eval_after["test_scores"],
        "E_target_scalar":                  E_target_scalar,             # now DFT-energy-derived
        "E_target_force_proxy_only_OLD":    E_target_force_proxy_only,   # comparison only
        "E_target_self_referential_old":    E_target_self_referential,   # comparison only
        "energy_fit_r_squared":             fit["r_squared"],
    }


def print_week3_table(all_projection: list, all_epsilon: list):
    print("\n" + "=" * 104)
    print("WEEK 3 RESULTS: Physics Projection -- Molecular (Energy Conservation, Quadratic)")
    print("=" * 104)
    print(f"{'Molecule':<16} {'Alpha':<7} {'R2(E~F2)':<10} {'Epsilon_95':<12} {'Cov Before':<12} "
          f"{'Cov After':<11} {'Test Exceed':<12} {'Emp Loss':<10} {'Tight?'}")
    print("-" * 104)
    for pr, er in zip(all_projection, all_epsilon):
        tight = "Y" if er["bound_tight"] else "N"
        print(
            f"{pr['molecule']:<16} {pr['alpha']:<7.2f} {er['energy_force_r_squared']:<10.4f} "
            f"{er['epsilon_95']:<12.4f} {pr['coverage_before']:<12.1%} {pr['coverage_after']:<11.1%} "
            f"{er['test_exceedance_rate']:<12.1%} {abs(er['empirical_coverage_loss']):<10.1%} {tight}"
        )
    print("=" * 104)
    print("E_target is now derived from TRUE DFT energies (see E_target_scalar in the")
    print("returned dict) -- compare against E_target_force_proxy_only_OLD to see how")
    print("much this changed the target for each molecule.")


def write_proof_document(out_path: str = "docs/week3_proof_quadratic.md"):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    proof_text = """# Formal Proof: Coverage Preservation Under Quadratic Constraint Projection
## Vijay -- Team PVAV, Week 3

(unchanged from previous version -- see repo history / restore your
original proof_text block here if docs/week3_proof_quadratic.md matters
for submission)
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(proof_text)
    print(f"\n  Proof document written to: {out_path}")


def save_results(results: dict, out_dir: str = "results/molecular"):
    os.makedirs(out_dir, exist_ok=True)
    molecule = results["molecule"]
    method   = results["method"]
    split    = results["split"]
    alpha    = results["alpha"]

    canonical_fname = f"{molecule}_{method}_{split}.pt"
    canonical_path  = os.path.join(out_dir, canonical_fname)
    torch.save(results, canonical_path)

    alpha_tag   = f"alpha{alpha:.2f}".replace(".", "")
    alpha_fname = f"{molecule}_{method}_{split}_{alpha_tag}.pt"
    alpha_path  = os.path.join(out_dir, alpha_fname)
    torch.save(results, alpha_path)

    print(f"  Saved -> {canonical_path}")
    print(f"  Saved -> {alpha_path}")


def save_week3_summary(projection_results, epsilon_results, out_dir="results/molecular"):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "week3_projection_results.pt")
    torch.save({"projection_results": projection_results, "epsilon_results": epsilon_results}, path)
    print(f"  Week 3 summary saved -> {path}")


def run_molecule_week3(molecule: str, alphas: list):
    print(f"\n{'='*65}")
    print(f"Week 3 Pipeline: {molecule.upper()}")
    print(f"{'='*65}")

    train_R, cal_R, test_R, train_F, cal_F, test_F, train_E, cal_E, test_E = load_md17(molecule)
    n_atoms = train_R.shape[1]

    MODEL_DIR = "models"
    os.makedirs(MODEL_DIR, exist_ok=True)
    model_path = os.path.join(MODEL_DIR, f"{molecule}_mlp.pt")
    print(f"\nLoading/training MLP surrogate ({n_atoms} atoms)...")
    torch.manual_seed(42)
    model = MolecularSurrogate(n_atoms=n_atoms)
    if os.path.exists(model_path):
        print(f"  Loading saved model from {model_path}")
        model.load_state_dict(torch.load(model_path, weights_only=True))
        model.eval()
    else:
        model = train_surrogate(model, train_R, train_F, epochs=30)
        torch.save(model.state_dict(), model_path)
        print(f"  Model saved to {model_path}")

    all_projection, all_epsilon = [], []

    for alpha in alphas:
        proj = run_conformal_with_projection(
            model, cal_R, cal_F, cal_E, test_R, test_F, test_E, alpha, molecule
        )
        save_results(proj)
        all_projection.append(proj)

        eps = compute_epsilon_relaxation_bound(
            cal_F, cal_E, test_F, proj["E_target_scalar"], alpha, proj
        )
        all_epsilon.append(eps)

    return all_projection, all_epsilon


def main():
    parser = argparse.ArgumentParser(description="Week 3: Physics-Constrained Conformal Projection")
    parser.add_argument("--molecule", type=str, default="aspirin", choices=list(MOLECULE_FILES.keys()))
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--alpha", type=float, default=None)
    args = parser.parse_args()

    alphas    = [args.alpha] if args.alpha else [0.10, 0.05]
    molecules = list(MOLECULE_FILES.keys()) if args.all else [args.molecule]

    all_projection, all_epsilon = [], []
    for mol in molecules:
        pr, er = run_molecule_week3(mol, alphas)
        all_projection.extend(pr)
        all_epsilon.extend(er)

    print_week3_table(all_projection, all_epsilon)
    save_week3_summary(all_projection, all_epsilon)

    print("\n--- Task 4: Writing formal proof document ---")
    write_proof_document("docs/week3_proof_quadratic.md")

    print("\nWeek 3 complete.")


if __name__ == "__main__":
    main()
