"""
Week 3: Physics-Constrained Conformal Projection (Molecular)
=============================================================
Vijay - Team PVAV

Tasks:
    1. Implement projection onto the energy-conservation constraint manifold
       for molecular dynamics (quadratic constraint -> closed-form projection).
       -> src/physics_projection.py: project_forces_energy_constraint()

    2. Apply projection to MD conformal sets. Measure empirical coverage
       before and after projection. Record coverage loss.
       -> run_conformal_with_projection() below

    3. Compute the epsilon relaxation bound: given calibration set's energy
       violation distribution, compute predicted coverage loss. Compare
       predicted vs. empirical coverage loss.
       -> src/physics_projection.py: compute_epsilon_relaxation_bound()

    4. Write formal proof for quadratic constraint case (energy conservation).
       -> docs/week3_proof_quadratic.md (generated by write_proof_document())

REVISION (post-Kiran feedback):
    E_target is now computed from TRUE calibration forces (cal_F), not the
    surrogate's own predictions (cal_pred). The original version was
    self-referential: it set the energy manifold target from the model's
    own output statistics, so the "constraint" measured consistency with
    the model rather than consistency with physical reality. This also
    fixes a real data bug: MD17 stores E with shape (N, 1), not (N,), and
    nothing in the original pipeline ever flattened it or used it, so the
    shape bug was never caught. fit_energy_force_relationship() in
    physics_projection.py now empirically checks how well ||F||^2 tracks
    true energy (R^2 ~ 0.35-0.42 across MD17 molecules: real but loose).

Usage:
    python molecular_week3.py                  # aspirin, alpha=0.10 and 0.05
    python molecular_week3.py --molecule ethanol
    python molecular_week3.py --all
    python molecular_week3.py --alpha 0.10

Output:
    results/molecular/<molecule>_conformal_projected_indist.pt            (canonical, last alpha run)
    results/molecular/<molecule>_conformal_projected_indist_alpha010.pt   (alpha=0.10, full record)
    results/molecular/<molecule>_conformal_projected_indist_alpha005.pt   (alpha=0.05, full record)
    results/molecular/week3_projection_results.pt
    docs/week3_proof_quadratic.md
"""

import argparse
import os
import sys
import time

import numpy as np
import torch
import torch.nn as nn

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
from conformal import SplitConformal, TrajectoryNormScore
from physics_projection import (
    compute_energy_from_forces,
    project_forces_energy_constraint_batched,
    compute_epsilon_relaxation_bound,
)


# ============================================================
# Data loading (same split as Week 2, now also loads energies)
# ============================================================

MOLECULE_FILES = {
    "aspirin":       "data/md17/md17_aspirin.npz",
    "ethanol":       "data/md17/md17_ethanol.npz",
    "uracil":        "data/md17/md17_uracil.npz",
    "malonaldehyde": "data/md17/md17_malonaldehyde.npz",
}


def load_md17(molecule: str, seed: int = 42):
    """Load MD17 with 70/15/15 split. Returns energies in addition to Week 2 outputs.

    NOTE: MD17 .npz files store E with shape (N, 1), not (N,). It gets
    flattened here -- if this flatten is removed, downstream regression
    and violation computations will silently break or raise shape errors.
    """
    path = MOLECULE_FILES[molecule]
    if not os.path.exists(path):
        raise FileNotFoundError(f"MD17 file not found: {path}")

    data = np.load(path)
    R = torch.tensor(data["R"], dtype=torch.float32)
    F = torch.tensor(data["F"], dtype=torch.float32)
    E_raw = data["E"]
    if E_raw.ndim > 1:
        print(f"  NOTE: raw E shape is {E_raw.shape}, flattening to 1D")
    E = torch.tensor(E_raw, dtype=torch.float32).reshape(-1)

    N = len(R)
    rng = np.random.RandomState(seed)
    idx = rng.permutation(N)
    n_train = int(0.70 * N)
    n_cal   = int(0.15 * N)
    train_idx = idx[:n_train]
    cal_idx   = idx[n_train : n_train + n_cal]
    test_idx  = idx[n_train + n_cal :]

    print(f"Molecule: {molecule}")
    print(f"  Total snapshots    : {N}")
    print(f"  Train / Cal / Test : {len(train_idx)} / {len(cal_idx)} / {len(test_idx)}")

    return (
        R[train_idx], R[cal_idx], R[test_idx],
        F[train_idx], F[cal_idx], F[test_idx],
        E[train_idx], E[cal_idx], E[test_idx],
    )


# ============================================================
# Surrogate model (same MLP as Week 2)
# ============================================================

class MolecularSurrogate(nn.Module):
    def __init__(self, n_atoms: int, hidden: int = 256, dropout_p: float = 0.1):
        super().__init__()
        self.n_atoms = n_atoms
        in_dim = n_atoms * 3
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden), nn.SiLU(), nn.Dropout(p=dropout_p),
            nn.Linear(hidden, hidden), nn.SiLU(), nn.Dropout(p=dropout_p),
            nn.Linear(hidden, hidden), nn.SiLU(), nn.Dropout(p=dropout_p),
            nn.Linear(hidden, in_dim),
        )

    def forward(self, R: torch.Tensor) -> torch.Tensor:
        batch = R.shape[0]
        return self.net(R.reshape(batch, -1)).reshape(batch, self.n_atoms, 3)


def train_surrogate(model, train_R, train_F, epochs=30, lr=1e-3, batch_size=64):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()
    N = len(train_R)
    model.train()
    for epoch in range(epochs):
        perm = torch.randperm(N)
        epoch_loss = 0.0
        for start in range(0, N, batch_size):
            idx = perm[start : start + batch_size]
            optimizer.zero_grad()
            loss = loss_fn(model(train_R[idx]), train_F[idx])
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * len(idx)
        if (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1:3d}/{epochs}  loss={epoch_loss/N:.6f}")
    model.eval()
    return model


def get_predictions(model, R, batch_size=256):
    model.eval()
    preds = []
    with torch.no_grad():
        for start in range(0, len(R), batch_size):
            preds.append(model(R[start : start + batch_size]))
    return torch.cat(preds, dim=0)


# ============================================================
# Task 2: Conformal prediction + projection pipeline
# ============================================================

def run_conformal_with_projection(
    model, cal_R, cal_F, cal_E, test_R, test_F, test_E, alpha, molecule
) -> dict:
    """
    Calibrate conformal predictor, then measure coverage before and after
    projecting test predictions onto the energy conservation manifold.

    The energy target is the mean ||F||^2 computed from the TRUE
    calibration FORCES (cal_F), not the model's predictions. Using
    predictions here was a real bug: it made the manifold target track
    the surrogate's own output statistics rather than physical reality,
    and the surrogate underpredicts force magnitude by as much as 85%
    on calibration data for some molecules (aspirin), so the old target
    was meaningfully wrong, not just imprecisely worded.

    Projection is closed-form: F_proj = F * sqrt(E_target / ||F||^2).
    """
    print(f"\n--- Conformal + Energy Projection (alpha={alpha}, target={1-alpha:.0%}) ---")

    cal_pred  = get_predictions(model, cal_R)
    test_pred = get_predictions(model, test_R)

    # Energy target from TRUE calibration forces, not model predictions.
    E_target_scalar = compute_energy_from_forces(cal_F).mean().item()
    E_target_self_referential = compute_energy_from_forces(cal_pred).mean().item()
    print(f"  Energy target (TRUE cal mean ||F||^2)        : {E_target_scalar:.4f}")
    print(f"  (old self-referential pred-based target was) : {E_target_self_referential:.4f}")

    score_fn = TrajectoryNormScore(normalize_by_length=True)
    cp = SplitConformal(score_fn, alpha=alpha)
    cp.calibrate(cal_pred, cal_F)

    eval_before     = cp.evaluate(test_pred, test_F)
    coverage_before = eval_before["coverage"]
    print(f"\n  Coverage BEFORE projection: {coverage_before:.1%}")

    print(f"  Projecting {len(test_pred)} test predictions onto energy manifold...")
    t0 = time.time()
    test_pred_projected = project_forces_energy_constraint_batched(
        test_pred, E_target_scalar
    )
    print(f"  Projection complete in {time.time() - t0:.1f}s")

    eval_after     = cp.evaluate(test_pred_projected, test_F)
    coverage_after = eval_after["coverage"]
    coverage_loss  = coverage_before - coverage_after
    print(f"  Coverage AFTER projection : {coverage_after:.1%}")
    print(f"  Empirical coverage loss   : {coverage_loss:+.1%}")

    return {
        "surrogate":               "molecular",
        "method":                  "conformal_projected",
        "split":                   "indist",
        "molecule":                molecule,
        "alpha":                   alpha,
        "coverage_before":         coverage_before,
        "coverage_after":          coverage_after,
        "coverage_loss_empirical": coverage_loss,
        "target_coverage":         1 - alpha,
        "mean_width_before":       eval_before["mean_width"],
        "mean_width_after":        eval_after["mean_width"],
        "threshold":               cp.threshold,
        "cal_scores":              cp.cal_scores,
        "n_cal":                   len(cal_R),
        "n_test":                  len(test_R),
        "test_pred_raw":           test_pred,
        "test_pred_projected":     test_pred_projected,
        "ground_truth":            test_F,
        "scores_before":           eval_before["test_scores"],
        "scores_after":            eval_after["test_scores"],
        "E_target_scalar":         E_target_scalar,
        "E_target_self_referential_old": E_target_self_referential,
    }


# ============================================================
# Results table
# ============================================================

def print_week3_table(all_projection: list, all_epsilon: list):
    print("\n" + "=" * 104)
    print("WEEK 3 RESULTS: Physics Projection -- Molecular (Energy Conservation, Quadratic)")
    print("=" * 104)
    print(f"{'Molecule':<16} {'Alpha':<7} {'R2(E~F2)':<10} {'Epsilon_95':<12} {'Cov Before':<12} "
          f"{'Cov After':<11} {'Pred Loss':<11} {'Emp Loss':<10} {'Tight?'}")
    print("-" * 104)
    for pr, er in zip(all_projection, all_epsilon):
        tight = "Y" if er["bound_tight"] else "N"
        print(
            f"{pr['molecule']:<16} {pr['alpha']:<7.2f} {er['energy_force_r_squared']:<10.4f} "
            f"{er['epsilon_95']:<12.4f} {pr['coverage_before']:<12.1%} {pr['coverage_after']:<11.1%} "
            f"{er['predicted_coverage_loss']:<11.1%} {abs(er['empirical_coverage_loss']):<10.1%} {tight}"
        )
    print("=" * 104)
    print("Y = bound tight (gap <= 3pp)   N = bound loose (report gap in paper)")
    print("R2(E~F2) = fit quality of ||F||^2 as an energy proxy on TRUE calibration data")


# ============================================================
# Task 4: Proof document
# ============================================================

def write_proof_document(out_path: str = "docs/week3_proof_quadratic.md"):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    proof_text = """# Formal Proof: Coverage Preservation Under Quadratic Constraint Projection
## Vijay -- Team PVAV, Week 3

---

## Setup

Let the surrogate model produce force predictions F_hat in R^(n_atoms x 3).
The energy conservation constraint is:

    g(F) = ||F||^2_F - E_target = 0

where E_target is the mean ||F||^2 computed from the TRUE calibration
forces (not the surrogate's predictions -- see the note on the proxy
below), and ||F||^2_F is the Frobenius norm squared (sum of squared force
components). This is a quadratic constraint because g is degree-2 in F.

The constraint manifold is:

    M = { F in R^(n_atoms x 3) : g(F) = 0 }

which is a sphere of radius sqrt(E_target) in force space.

---

## Note on the Energy Proxy

||F||^2 is not literal total energy. It is used as a proxy under a
harmonic (quadratic) approximation: near a local minimum, energy above
the minimum is proportional to squared displacement, and force is
proportional to displacement, so squared force is proportional to energy
above the minimum. This approximation is checked empirically, not
assumed. fit_energy_force_relationship() (src/physics_projection.py)
fits true calibration energy against true ||F||^2 after removing the
large DFT baseline offset from E, and reports R^2. Across the four MD17
molecules this comes out to roughly 0.35-0.42: the proxy is real
(consistent positive correlation, not noise) but loose (it explains under
half the true energy variance). Any coverage-preservation claim below
should be read with that caveat, not as a statement about exact energy
conservation.

---

## Closed-Form Projection

Unlike gradient-based projection, the sphere admits an exact closed-form solution.
The closest point on M to any F_pred is:

    pi_M(F_pred) = F_pred * sqrt(E_target / ||F_pred||^2)

This scales F_pred to lie exactly on the sphere while minimizing L2 distance.

---

## Theorem (Epsilon-Relaxed Coverage Under Quadratic Projection)

Let C_alpha be a valid (1-alpha) conformal prediction set for forces,
satisfying:

    P(F_true in C_alpha) >= 1 - alpha

Let pi_M(F) denote the closed-form projection onto M.
Let C_alpha_proj = { pi_M(F) : F in C_alpha } be the projected set.

### Exact case (epsilon = 0)

If the true simulator satisfies the energy constraint exactly
(F_true in M for all test inputs), then:

    P(F_true in C_alpha_proj) >= 1 - alpha

Proof sketch: If F_true in M and F_true in C_alpha, then pi_M(F_true) = F_true
(projection is identity on M), so F_true in C_alpha_proj.
Since P(F_true in C_alpha) >= 1 - alpha and the event {F_true in C_alpha_proj}
contains the event {F_true in C_alpha, F_true in M}:

    P(F_true in C_alpha_proj) >= P(F_true in C_alpha) - P(F_true not in M)
                               >= (1 - alpha) - 0
                               = 1 - alpha   QED

### Epsilon-relaxed case

In practice, real simulators satisfy constraints only approximately. Let:

    epsilon_i = | ||F_true_i||^2 - E_target | / E_target

Define the epsilon-relaxed manifold:

    M_epsilon = { F : |g(F)| / E_target <= epsilon }

Then:

    P(F_true in C_alpha_proj) >= (1 - alpha) - P(F_true not in M_epsilon)

Proof sketch:
    P(F_true in C_alpha_proj)
        >= P(F_true in C_alpha, F_true in M_epsilon)
        >= P(F_true in C_alpha) - P(F_true not in M_epsilon)
        >= (1 - alpha) - P(F_true not in M_epsilon)   QED

---

## Curvature Effects (Quadratic Case)

The sphere manifold M is curved with principal curvature kappa = 1/sqrt(E_target).
The projection can distort distances by at most (1 + kappa * delta) where delta
is the distance from F to M. The full bound becomes:

    coverage_loss <= P(F_true not in M_epsilon)
                   + kappa * epsilon * E[||F_true - pi_M(F_true)||]

In practice kappa is small (E_target >> 1 in force-squared units), so the
curvature correction is negligible.

---

## Empirical Validation

We validate by:
1. Confirming ||F||^2 actually relates to true energy E on calibration
   data, via the linear fit and R^2 described above in "Note on the
   Energy Proxy." This is run on TRUE forces and TRUE energies only, never
   on model predictions, since that would conflate proxy validity with
   model accuracy.
2. Setting E_target from TRUE calibration forces, not the surrogate's
   own predictions.
3. Computing epsilon_95 = 95th percentile of TRUE calibration energy
   violations relative to E_target.
4. Predicted coverage loss = fraction of TRUE calibration set with
   violation > epsilon_95 (~5% by construction).
5. Comparing predicted coverage loss to empirical coverage loss
   (coverage_before - coverage_after) on the test set.

See results/molecular/week3_projection_results.pt for numerical values,
including R^2 and correlation per molecule.

---

## Connection to Other Proofs

- Linear case (mass conservation, weather domain): Projection onto a
  linear subspace is exact (no curvature), so coverage is preserved
  exactly when epsilon = 0.
- Equivariance case (molecular domain): Group-averaging projection;
  coverage loss bounded by the surrogate's equivariance violation.
- This proof (quadratic, energy conservation): Coverage loss bounded by
  epsilon plus curvature correction, with the underlying proxy's validity
  itself empirically checked rather than assumed. Validated above.
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(proof_text)
    print(f"\n  Proof document written to: {out_path}")


# ============================================================
# Save helpers
# ============================================================

def save_results(results: dict, out_dir: str = "results/molecular"):
    """
    Save results dict to .pt file.

    Writes TWO files:
    1. A canonical filename with no alpha suffix, kept for backward
       compatibility with molecular_week4.py, which loads this exact path.
       This file reflects whichever alpha was saved most recently in the
       run loop (alpha=0.05 / 95% target, given the default alpha order).
    2. An alpha-suffixed filename, so BOTH alpha=0.10 and alpha=0.05
       results are preserved on disk. The original version only wrote the
       canonical filename, so the 90% target results were silently
       overwritten by the 95% target run every time -- this is fixed here.
    """
    os.makedirs(out_dir, exist_ok=True)
    molecule = results["molecule"]
    method   = results["method"]
    split    = results["split"]
    alpha    = results["alpha"]

    canonical_fname = f"{molecule}_{method}_{split}.pt"
    canonical_path  = os.path.join(out_dir, canonical_fname)
    torch.save(results, canonical_path)

    alpha_tag   = f"alpha{alpha:.2f}".replace(".", "")
    alpha_fname = f"{molecule}_{method}_{split}_{alpha_tag}.pt"
    alpha_path  = os.path.join(out_dir, alpha_fname)
    torch.save(results, alpha_path)

    print(f"  Saved -> {canonical_path}")
    print(f"  Saved -> {alpha_path}")


def save_week3_summary(projection_results, epsilon_results, out_dir="results/molecular"):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "week3_projection_results.pt")
    torch.save({"projection_results": projection_results, "epsilon_results": epsilon_results}, path)
    print(f"  Week 3 summary saved -> {path}")


# ============================================================
# Main
# ============================================================

def run_molecule_week3(molecule: str, alphas: list):
    print(f"\n{'='*65}")
    print(f"Week 3 Pipeline: {molecule.upper()}")
    print(f"{'='*65}")

    train_R, cal_R, test_R, train_F, cal_F, test_F, train_E, cal_E, test_E = load_md17(molecule)
    n_atoms = train_R.shape[1]

    MODEL_DIR = "models"
    os.makedirs(MODEL_DIR, exist_ok=True)
    model_path = os.path.join(MODEL_DIR, f"{molecule}_mlp.pt")
    print(f"\nLoading/training MLP surrogate ({n_atoms} atoms)...")
    torch.manual_seed(42)
    model = MolecularSurrogate(n_atoms=n_atoms)
    if os.path.exists(model_path):
        print(f"  Loading saved model from {model_path}")
        model.load_state_dict(torch.load(model_path, weights_only=True))
        model.eval()
    else:
        model = train_surrogate(model, train_R, train_F, epochs=30)
        torch.save(model.state_dict(), model_path)
        print(f"  Model saved to {model_path}")

    all_projection, all_epsilon = [], []

    for alpha in alphas:
        proj = run_conformal_with_projection(
            model, cal_R, cal_F, cal_E, test_R, test_F, test_E, alpha, molecule
        )
        save_results(proj)
        all_projection.append(proj)

        eps = compute_epsilon_relaxation_bound(
            cal_F, cal_E, proj["E_target_scalar"], alpha, proj
        )
        all_epsilon.append(eps)

    return all_projection, all_epsilon


def main():
    parser = argparse.ArgumentParser(description="Week 3: Physics-Constrained Conformal Projection")
    parser.add_argument("--molecule", type=str, default="aspirin", choices=list(MOLECULE_FILES.keys()))
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--alpha", type=float, default=None)
    args = parser.parse_args()

    alphas    = [args.alpha] if args.alpha else [0.10, 0.05]
    molecules = list(MOLECULE_FILES.keys()) if args.all else [args.molecule]

    all_projection, all_epsilon = [], []
    for mol in molecules:
        pr, er = run_molecule_week3(mol, alphas)
        all_projection.extend(pr)
        all_epsilon.extend(er)

    print_week3_table(all_projection, all_epsilon)
    save_week3_summary(all_projection, all_epsilon)

    print("\n--- Task 4: Writing formal proof document ---")
    write_proof_document("docs/week3_proof_quadratic.md")

    print("\nWeek 3 complete.")
    print("  results/molecular/  <- projection results + week3 summary")
    print("  docs/week3_proof_quadratic.md  <- formal proof")
    print("Share results table with Vasilisa for the physics projection aggregation.")


if __name__ == "__main__":
    main()
